'use strict';
let chatController=null,chatRequestId=null,chatDraftTimer=null,chatDraftDirty=false,chatProfile=null,recognition=null;
const icon=name=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS('http://www.w3.org/2000/svg','use');use.setAttribute('href','#i-'+name);svg.append(use);svg.setAttribute('aria-hidden','true');return svg;};
function chatModeUI(){document.body.dataset.mode=state.mode;updateWelcome();if(state.mode==='chat'){$('prompt').placeholder='Digite sua mensagem…';$('action-hint').textContent='';$('step-label').textContent='';$('send').setAttribute('aria-label','Enviar mensagem');$('send').replaceChildren(icon('send'));}else document.body.classList.remove('welcome-state');$('voice-input').hidden=state.mode!=='chat'||!(window.SpeechRecognition||window.webkitSpeechRecognition);}
function updateWelcome(){const welcome=state.mode==='chat'&&!(state.chatMessages?.length);$('welcome').hidden=!welcome;document.body.classList.toggle('welcome-state',welcome);}
async function updateSidebar(){state.conversations=await api('conversations');renderSidebar();}
function renderSidebar(){const root=$('recent-conversations');root.replaceChildren();for(const c of state.conversations||[]){const b=button('',async()=>{if(state.busy)return;await saveChatDraft();await save();await loadProject(c.project_id,{conversationId:c.id});closeSidebar();},'conversation-link');b.append(icon('chat'),el('span',c.title));const time=el('time',new Date(c.updated_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}));time.dateTime=new Date(c.updated_at).toISOString();b.append(time);b.setAttribute('aria-current',String(c.id===state.conversationId));b.title=c.title;root.append(b);}if(!root.children.length)root.append(el('p','Suas conversas aparecerão aqui.','sidebar-empty'));}
async function openProjectConversation(preferred){await updateSidebar();let c=preferred?state.conversations.find(c=>c.id===preferred&&c.project_id===state.id):state.conversations.find(c=>c.project_id===state.id);if(!c){const created=await api('conversations',{method:'POST',body:{projectId:state.id}});c={id:created.id};await updateSidebar();}const data=await api('conversations/'+c.id);state.conversationId=c.id;state.conversation=data.conversation;state.chatMessages=data.messages;$('older-messages').hidden=!data.hasMore;chatDraftDirty=false;state.mode='chat';$('prompt').value=data.conversation.draft||'';state.chatDraft=$('prompt').value;history.replaceState(null,'','#c-'+c.id);$('empty').hidden=true;$('review').hidden=true;$('result').hidden=true;$('photo-view').hidden=true;$('editor-view').hidden=true;$('chat-view').hidden=false;setStep('chat');modeButtons();renderChatMessages();renderSidebar();resizeText();}
async function newConversation(){if(state.busy)return;await saveChatDraft();await save();const c=await api('conversations',{method:'POST',body:{projectId:state.id}});await openProjectConversation(c.id);closeSidebar();$('prompt').focus();}
function draftChanged(){state.chatDraft=$('prompt').value;chatDraftDirty=true;clearTimeout(chatDraftTimer);chatDraftTimer=setTimeout(()=>handle(saveChatDraft),900);}
async function saveChatDraft(){clearTimeout(chatDraftTimer);if(!chatDraftDirty||!state.conversationId)return;const id=state.conversationId,draft=state.chatDraft;await api('conversations/'+id,{method:'PATCH',body:{draft}});if(state.conversationId===id&&state.chatDraft===draft)chatDraftDirty=false;}
function richText(target,text){target.replaceChildren();for(const line of text.split('\n')){const p=el('div');if(/^[-*] /.test(line))p.className='text-list-item';const value=line.replace(/^[-*] /,'• ');for(const part of value.split(/(\*\*[^*]+\*\*)/g)){if(part.startsWith('**')&&part.endsWith('**'))p.append(el('strong',part.slice(2,-2)));else p.append(document.createTextNode(part));}if(!line)p.append(document.createElement('br'));target.append(p);}}
function renderChatMessages(){const log=$('chat-log'),nearBottom=$('workspace').scrollHeight-$('workspace').scrollTop-$('workspace').clientHeight<180;log.replaceChildren();for(const m of state.chatMessages||[]){const row=el('article',undefined,'chat-message '+m.role),content=el('div',undefined,'chat-message-content');row.dataset.message=m.id;row.append(el('span',m.role==='user'?'Você':m.role==='notice'?'Aviso do sistema':'Veyro IA','message-author'));const body=el('div',undefined,'message-body');richText(body,m.text|| (m.status==='RUNNING'?'Veyro está pensando…':''));content.append(body);
 for(const a of m.attachments||[]){const link=el('a',a.name,'message-file');link.href='/api/projects/'+state.id+'/assets/'+a.id;link.target='_blank';link.rel='noopener';content.append(link);}
 if(m.tool)content.append(toolCard(m.tool));
 if(m.status==='RUNNING'){const status=el('small','Respondendo…','reply-state');status.setAttribute('role','status');content.append(status);}else if(['FAILED','CANCELLED','WAITING'].includes(m.status)){content.append(el('small',m.status==='FAILED'?'Resposta não concluída':m.status==='CANCELLED'?'Resposta interrompida':'Aguardando conexão','reply-state'));const userMessage=[...(state.chatMessages||[])].reverse().find(x=>x.role==='user'&&x.created_at<=m.created_at);if(userMessage&&!m.tool)content.append(button('Tentar novamente',()=>sendChat(userMessage.text,userMessage.attachments?.map(a=>a.id)),'retry-button'));}
 row.append(content);log.append(row);}updateWelcome();if(nearBottom)$('workspace').scrollTop=$('workspace').scrollHeight;}
function toolCard(tool){if(tool.type==='research')return researchCard(tool);const card=el('section',undefined,'chat-tool-card');if(tool.type==='editor'){card.append(icon('video'),el('h3','Edição de vídeo'),el('p',tool.request||'Pedido de edição preparado.'),button('Abrir editor',()=>studioRoute('editor',tool.request||''),'small-button'));return card;}
 card.append(icon('image'),el('h3',tool.needsSource?'Escolha a foto para editar':'Pedido de imagem'),el('p',tool.prompt||''));
 const job=state.photoJobs?.find(j=>j.id===tool.jobId);if(job){card.append(el('small',job.outputs.length+' de '+job.request.count+' imagem(ns) · '+({WAITING:'aguardando conexão',COMPLETE:'prontas para revisar',PARTIAL:'parcial salvo',FAILED:'não concluído',QUEUED:'preparado',RUNNING:'gerando',CANCELLED:'cancelado'}[job.status]||job.status)));const grid=el('div',undefined,'inline-images');for(const o of job.outputs){const a=state.allAssets.find(a=>a.id===o.assetId);if(a){const link=el('a');link.href='/api/projects/'+state.id+'/assets/'+a.id;link.target='_blank';link.rel='noopener';link.append(media(a));grid.append(link);}}card.append(grid);if(state.images&&['WAITING','QUEUED','PARTIAL'].includes(job.status))card.append(button('Gerar '+(job.request.count-job.outputs.length)+' imagem(ns)',async()=>{await processPhoto(job.id);renderChatMessages();},'small-button'));}
 else card.append(el('small',tool.needsSource?'Adicione a foto pelo + e escolha a referência.':'Pedido salvo no Photo Studio.'));
 card.append(button('Ajustar pedido',()=>studioRoute('photo',tool.prompt||''),'small-button'));return card;
}
function updateStreamingBody(message){const row=[...$('chat-log').children].find(el=>el.dataset.message===message.id);if(row)richText(row.querySelector('.message-body'),message.text);else renderChatMessages();const workspace=$('workspace');if(workspace.scrollHeight-workspace.scrollTop-workspace.clientHeight<240)workspace.scrollTop=workspace.scrollHeight;}
async function readChatStream(response,onEvent){if(!response.ok){const e=await response.json();throw Error(e.error||'Não foi possível enviar.');}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',terminal=false;try{for(;;){const {value,done}=await reader.read();buffer+=done?decoder.decode():decoder.decode(value,{stream:true});buffer=buffer.replace(/\r/g,'');let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const event=block.split('\n').find(l=>l.startsWith('event:'))?.slice(6).trim();const data=block.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5)).join('\n');if(event&&data){const parsed=JSON.parse(data);await onEvent(event,parsed);if(['done','waiting','error','cancelled'].includes(event))terminal=true;}}if(done)break;}if(!terminal)throw Error('A conexão caiu antes de concluir a resposta.');}finally{reader.releaseLock();}}
async function sendChat(text,attachmentIds){if(state.busy||!state.conversationId)return;if(!text&&!state.files.length)throw Error('Escreva uma mensagem ou adicione um arquivo.');await saveChatDraft();await save();const cid=state.conversationId,requestId=crypto.randomUUID(),now=Date.now(),ids=attachmentIds||state.files.map(f=>f.id),assistant={id:requestId,role:'assistant',text:'',status:'RUNNING',created_at:now+1};
 state.chatMessages.push({id:requestId+'-user',role:'user',text,status:'COMPLETE',attachments:state.allAssets.filter(a=>ids.includes(a.id)),created_at:now},assistant);renderChatMessages();$('workspace').scrollTop=$('workspace').scrollHeight;busy(true);$('new-chat').disabled=true;$('prompt').disabled=true;$('stop-response').hidden=false;$('send').hidden=true;chatController=new AbortController();chatRequestId=requestId;feedback('');
 let accepted=false;
 try{const response=await fetch('/api/conversations/'+cid+'/messages',{method:'POST',headers:{'Content-Type':'application/json','X-Veyro-Request':'1'},body:JSON.stringify({requestId,message:text,attachments:ids,researchMode:state.researchMode||'STANDARD'}),signal:chatController.signal});await readChatStream(response,async(event,data)=>{
  if(event==='status'){accepted=true;$('prompt').value='';state.chatDraft='';chatDraftDirty=false;state.conversation.title=data.title;resizeText();}
  if(event==='research_status'){feedback(({SEARCHING:'Pesquisando…',READING:'Lendo as fontes…',VERIFYING:'Verificando fontes…'})[data.status]||'Preparando pesquisa…');const row=[...$('chat-log').children].find(n=>n.dataset.message===assistant.id);if(row)row.querySelector('.message-body').textContent=$('feedback').textContent;}
  if(event==='token'){assistant.text+=data.text;updateStreamingBody(assistant);}
  if(event==='notice'){assistant.role=data.role||'notice';assistant.text=data.text;renderChatMessages();}
  if(event==='tool'){assistant.tool=data;renderChatMessages();}
  if(event==='done')assistant.status='COMPLETE';if(event==='waiting')assistant.status='WAITING';if(event==='cancelled')assistant.status='CANCELLED';if(event==='error'){assistant.status='FAILED';feedback(data.message,true);}
 });}
 catch(e){assistant.status=e.name==='AbortError'?'CANCELLED':'FAILED';feedback(e.name==='AbortError'?'Resposta interrompida.':e.message||'Não foi possível enviar.',e.name!=='AbortError');if(!accepted){$('prompt').value=text;state.chatDraft=text;chatDraftDirty=true;}}
 finally{chatRequestId=null;chatController=null;busy(false);$('new-chat').disabled=false;$('prompt').disabled=false;$('stop-response').hidden=true;$('send').hidden=false;try{const data=await api('conversations/'+cid);state.chatMessages=data.messages;if(!accepted&&data.messages.some(m=>m.id===requestId)){state.chatDraft=data.conversation.draft;$('prompt').value=state.chatDraft;chatDraftDirty=false;}await refreshDetails();await updateSidebar();}catch{}renderChatMessages();resizeText();}
}
async function stopResponse(){if(!chatRequestId)return;const id=chatRequestId;try{await api('conversations/'+state.conversationId+'/cancel',{method:'POST',body:{requestId:id}});}finally{chatController?.abort();}}
function closeSidebar(){document.body.classList.remove('sidebar-open');$('sidebar-overlay').hidden=true;$('sidebar-toggle').setAttribute('aria-expanded','false');$('sidebar').removeAttribute('aria-modal');if(innerWidth<900)$('sidebar').setAttribute('inert','');}
function toggleSidebar(){const mobile=innerWidth<900;if(mobile){const open=!document.body.classList.contains('sidebar-open');document.body.classList.toggle('sidebar-open',open);$('sidebar-overlay').hidden=!open;$('sidebar-toggle').setAttribute('aria-expanded',String(open));if(open){$('sidebar').removeAttribute('inert');$('sidebar').setAttribute('role','dialog');$('sidebar').setAttribute('aria-modal','true');$('sidebar-close').focus();}else closeSidebar();}else{document.body.classList.toggle('sidebar-collapsed');$('sidebar-toggle').setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-collapsed')));}}
async function loadProfile(){chatProfile=await api('profile');$('profile-name').textContent=chatProfile.name;$('profile-open').setAttribute('aria-label','Abrir perfil de '+chatProfile.name);const avatar=$('profile-avatar');avatar.replaceChildren();if(chatProfile.avatar){const img=el('img');img.src='/api/profile/avatar?v='+chatProfile.updatedAt;img.alt='Foto do perfil';avatar.append(img);}else avatar.append(icon('user'));}
async function profilePanel(){await loadProfile();const root=openPanel('Meu perfil'),name=el('input');name.value=chatProfile.name;name.maxLength=80;name.setAttribute('aria-label','Seu nome');const photo=el('input');photo.type='file';photo.accept='image/png,image/jpeg,image/webp';photo.setAttribute('aria-label','Escolher foto do perfil');photo.onchange=()=>handle(async()=>{const file=photo.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Use uma foto de até 2 MB.');const form=new FormData();form.set('file',file);await api('profile/avatar',{method:'POST',body:form});await loadProfile();feedback('Foto do perfil atualizada.');});root.append(el('label','Nome'),name,button('Salvar nome',async()=>{await api('profile',{method:'PUT',body:{name:name.value}});await loadProfile();feedback('Perfil salvo.');}),el('p','Foto do perfil · JPG, PNG ou WebP, até 2 MB.','pending-note'),photo);}
function projectOptions(){const root=openPanel('Conversa e projeto'),title=el('input');title.value=state.conversation?.title||'Nova conversa';title.maxLength=80;title.setAttribute('aria-label','Título da conversa');root.append(title,button('Renomear conversa',async()=>{await api('conversations/'+state.conversationId,{method:'PATCH',body:{title:title.value}});await updateSidebar();state.conversation.title=title.value; $('panel').close();}),button('Trocar projeto',projects),button('Memórias',knowledgeMemories),button('Versões do projeto',versions),button('Atividade e conexão',activity),button('Arquivar conversa',archiveCurrent),button('Excluir conversa',deleteCurrentPanel,'danger-button'));}
function agentsPanel(){const root=openPanel('Agentes e recursos');for(const [name,status,description]of [['Veyro Core',state.chat?'Modelo configurado':'Aguardando modelo','Conversa, contexto e preparação de pedidos.'],['Photo Studio',state.images?'Gerador configurado':'Aguardando gerador','Pedidos de criação e edição de imagens.'],['Editor','Controles disponíveis','Cortes, velocidade e montagem de vídeos enviados.'],['Qualidade','Verificação básica','Valida parâmetros. A avaliação visual automática ainda não está conectada.']]){const card=el('article',undefined,'memory-card');card.append(el('strong',name),el('small',status),el('p',description));root.append(card);}}
function initChat(){state.chatMessages=[];state.conversations=[];state.conversationId=null;state.chatDraft='';$('new-chat').onclick=()=>handle(newConversation);$('home-chat').onclick=()=>handle(()=>changeMode('chat'));$('sidebar-toggle').onclick=toggleSidebar;$('sidebar-overlay').onclick=closeSidebar;$('sidebar-close').onclick=closeSidebar;
 $('nav-images').onclick=()=>handle(async()=>{await changeMode('photo');closeSidebar();});$('nav-videos').onclick=()=>{const root=openPanel('Vídeos');root.append(button('Planejar um vídeo',async()=>{await changeMode('create');$('panel').close();closeSidebar();}),button('Editar um vídeo enviado',async()=>{await changeMode('editor');$('panel').close();closeSidebar();}));};$('nav-agents').onclick=agentsPanel;$('profile-open').onclick=()=>handle(profilePanel);$('project-options').onclick=projectOptions;$('stop-response').onclick=()=>handle(stopResponse);
 for(const b of document.querySelectorAll('[data-suggestion]'))b.onclick=()=>{$('prompt').value=b.dataset.suggestion;draftChanged();resizeText();$('prompt').focus();};for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>handle(()=>changeMode(b.dataset.action==='plan'?'create':'editor'));
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;$('voice-input').hidden=!Speech;if(Speech){$('voice-input').onclick=()=>{if(recognition){recognition.stop();return;}recognition=new Speech();recognition.lang='pt-BR';recognition.interimResults=false;recognition.onresult=e=>{$('prompt').value+=($('prompt').value?' ':'')+e.results[0][0].transcript;$('prompt').dispatchEvent(new Event('input'));};recognition.onerror=()=>feedback('Não foi possível usar o microfone. Você pode digitar.',true);recognition.onend=()=>{recognition=null;$('voice-input').classList.remove('recording');};recognition.start();$('voice-input').classList.add('recording');};}
 $('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&innerWidth>=900){e.preventDefault();$('composer').requestSubmit();}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();if(e.key==='Tab'&&innerWidth<900&&document.body.classList.contains('sidebar-open')){const nodes=[...$('sidebar').querySelectorAll('button:not([disabled])')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 const responsive=()=>{if(innerWidth>=900){$('sidebar').removeAttribute('inert');$('sidebar').removeAttribute('aria-modal');$('sidebar').removeAttribute('role');$('sidebar-overlay').hidden=true;}else if(!document.body.classList.contains('sidebar-open'))closeSidebar();};window.addEventListener('resize',responsive);responsive();handle(loadProfile);
}
